apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jpqf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-jpqf@sha256:0927f2e0465691ccc8fa012a4ae28a7c56d42f17aa712471efdeedb38c9f0974
        name: my-nodejs
        resources: {}
status: {}
